package havadurumu;
// Generated 20.�ub.2017 14:43:57 by Hibernate Tools 4.3.1

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Hdurumu generated by hbm2java
 */
@Entity
@Table(name = "Hdurumu",
         schema = "dbo",
         catalog = "deneme2"
)
public class Hdurumu implements java.io.Serializable {

    private int id;
    private String time;
    private Double max;
    private Double min;
    private String location;

    public Hdurumu() {
    }

    public Hdurumu(int id) {
        this.id = id;
    }

    public Hdurumu(int id, String time, Double max, Double min, String location) {
        this.id = id;
        this.time = time;
        this.max = max;
        this.min = min;
        this.location = location;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    @Column(name = "ID", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "time", length = 31)
    public String getTime() {
        return this.time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    @Column(name = "max", precision = 53, scale = 0)
    public Double getMax() {
        return this.max;
    }

    public void setMax(Double max) {
        this.max = max;
    }

    @Column(name = "min", precision = 53, scale = 0)
    public Double getMin() {
        return this.min;
    }

    public void setMin(Double min) {
        this.min = min;
    }

   @Column(name = "location", length = 31)
    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

}
